# Generated by Django 2.2.3 on 2019-08-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
